= Wrapping Text to Fit Shaped Containers with CSS
Jonathan Skeate <skeate@gmail.com>
:published-at: 2014-11-29
:hp-tags: css, css3, demo

[.lead]
With CSS, http://nicolasgallagher.com/pure-css-gui-icons/demo/#non[you
can make all kinds of shapes], but if you try to put any text inside
even a simple non-rectangular shape, you can run into problems. The text
will not wrap to fit inside the container.

+++
<p data-height="268" data-theme-id="16793" data-slug-hash="raOVjY" data-default-tab="result" data-user="skeate" class='codepen'>See the Pen <a href='http://codepen.io/skeate/pen/raOVjY/'>raOVjY</a> by Jonathan Skeate (<a href='http://codepen.io/skeate'>@skeate</a>) on <a href='http://codepen.io'>CodePen</a>.</p>
+++

However, recently I discovered the
https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside[CSS
property `shape-outside`]. Browser support isn’t great (currently only
Webkit-based browsers), but there is a
https://github.com/adobe-webplatform/css-shapes-polyfill[polyfill]. It
allows you to wrap text around a floated element, as if it had a shape
you specify. Perhaps the most common example is a circle:

+++
<p data-height="268" data-theme-id="16793" data-slug-hash="qEOdrM" data-default-tab="result" data-user="skeate" class='codepen'>See the Pen <a href='http://codepen.io/skeate/pen/qEOdrM/'>qEOdrM</a> by Jonathan Skeate (<a href='http://codepen.io/skeate'>@skeate</a>) on <a href='http://codepen.io'>CodePen</a>.</p>
+++

Gorgeous. But how does this help with the original problem? This handles
wrapping outside a shape. There’s no `shape-inside`
(http://dev.w3.org/csswg/css-shapes-2/#shape-inside-property[yet]).

Until that arrives, we can still manage this. The trick lies in
inverting the `shape-outside`. In other words, make the shape a polygon,
with two points at (0,0) and (0, 100%), and the rest following the
contour of the desired shape. It’s not perfect (for circles at least)
but it’s good enough, since text would never be perfect anyway.

One caveat: this only works with floated elements. We can float the
`::before` pseudoelement just fine, but if we try to float the
`::after`, it doesn’t look right. See the example below — you can hover
over the circle to color the pseudoelements, to make it more obvious
what’s happening.

+++
<p data-height="268" data-theme-id="16793" data-slug-hash="gbarrN" data-default-tab="result" data-user="skeate" class='codepen'>See the Pen <a href='http://codepen.io/skeate/pen/gbarrN/'>gbarrN</a> by Jonathan Skeate (<a href='http://codepen.io/skeate'>@skeate</a>) on <a href='http://codepen.io'>CodePen</a>.</p>
+++

Unfortunately the only way I’ve found around it so far is
double-wrapping the circle element, so you can use both `::before`s.
Forgiveable, I suppose, but I would like a single-element solution.

+++
<p data-height="268" data-theme-id="16793" data-slug-hash="YPyqWd" data-default-tab="result" data-user="skeate" class='codepen'>See the Pen <a href='http://codepen.io/skeate/pen/YPyqWd/'>YPyqWd</a> by Jonathan Skeate (<a href='http://codepen.io/skeate'>@skeate</a>) on <a href='http://codepen.io'>CodePen</a>.</p>
+++

Here’s an SCSS mixin to handle it all:

[source,scss]
@mixin circle($radius){
  width: $radius*2;
  height: $radius*2;
  border-radius: $radius;
  &::before{
    content: '';
    height: 100%;
    width: 50%;
    float: left;
    shape-outside: polygon(
      0 0, 100% 0, 60% 4%, 40% 10%, 20% 20%, 10% 28.2%, 5% 34.4%, 0 50%,
      5% 65.6%, 10% 71.8%, 20% 80%, 40% 90%, 60% 96%, 100% 100%, 0 100%
    );
  }
  > span::before{
    content: '';
    height: 100%;
    width: 50%;
    float: right;
    shape-outside: polygon(
      100% 0, 0 0, 40% 4%, 60% 10%, 80% 20%, 90% 28.2%, 95% 34.4%, 100% 50%,
      95% 65.6%, 90% 71.8%, 80% 80%, 60% 90%, 40% 96%, 0 100%, 100% 100%
    );
  }
}

+++
<script async src="//assets.codepen.io/assets/embed/ei.js"></script>
+++